### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by gjsduarte**
Some minor refactors and typo fixes

### CODE REVIEW

**Review by xplosunn — COMMENTED** [review]
Needs to be updated to CircleCI v2. This change could be done in another PR or in this one.

**Comment by rtfpessoa** [comment]
@gjsduarte also this Builder code is kind of outdated and should use the one in codacy-engine-scala-seed.

**Comment by rtfpessoa** [comment]
@gjsduarte do we want to keep this?

**Comment by gjsduarte** [comment]
No I guess not.

**Pull request closed without merging**
